Added comman to update Alpine system

diff --git a/scripts/rainbow-upgradesystem b/scripts/rainbow-upgradesystem
--- a/scripts/rainbow-upgradesystem
+++ b/scripts/rainbow-upgradesystem
@@ -22,11 +22,62 @@ output_message() {
   echo ${1}
 }
 
+
+# Upgrade system packages on Alpine-like systems, via normal apk
+upgrade_on_alpine() {
+  local tmp_apk_full_output=$(mktemp)
+  # Command ouput is in format
+  # fetch http://debian.ethz.ch/alpine/v3.22/main/x86_64/APKINDEX.tar.gz
+  # fetch http://debian.ethz.ch/alpine/v3.22/community/x86_64/APKINDEX.tar.gz
+  # (1/12) Upgrading runc (1.3.0-r1 -> 1.3.0-r2)
+  # (2/12) Upgrading containerd (2.1.3-r0 -> 2.1.3-r1)
+  # (3/12) Upgrading glib (2.84.3-r0 -> 2.84.4-r0)
+  # Executing busybox-1.37.0-r19.trigger
+  # Executing glib-2.84.4-r0.trigger
+  # OK: 469 MiB in 142 packages
+
+  # Capture the whole command output
+  apk -U upgrade > ${tmp_apk_full_output} 2>&1
+  # Save the exit code of the command in a variable
+  local apk_exit_code=$?
+
+  # Check if the upgrade went well
+  if [ ${apk_exit_code} -eq 0 ]; then
+    # All good, packages were upgraded, or no packages to upgrade
+
+    # Captures potentially upgraded packages
+    local tmp_file1=$(mktemp)
+    grep 'Upgrading ' ${tmp_apk_full_output} | awk '{print $3}' > ${tmp_file1} 2>&1
+
+    # File exists and has a size greater than zero 
+    if [ -s ${tmp_file1} ]; then
+      output_message "Notify about packages to upgrade..."
+      local tmp_file2=$(mktemp)
+      echo "Packages to upgrade:" > ${tmp_file2}
+      cat ${tmp_file1} >> ${tmp_file2}
+      cat ${tmp_file2} | rainbow-notifytelegram
+      output_message " System upgrade done!"
+    else
+      output_message "No packages to upgrade"
+    fi
+    rm -f ${tmp_apk_full_output}
+    rm -f ${tmp_file1}
+    rm -f ${tmp_file2}
+
+  else
+    output_message "Error in upgrading packages..."
+    cat "Error in the apk command, check ${tmp_apk_full_output}" | rainbow-notifytelegram
+  fi
+
+
+  rm -f ${tmp_file1}
+}
+
 # Upgrade system packages on Debian-like systems, via normal apt
 upgrade_on_debian() {
   local tmp_file1=$(mktemp)
   apt update > /dev/null 2>&1
-  # output format is 
+  # Command output format is 
   # frr-pythontools/stable 10.2.3-1+pve1 all [upgradable from: 10.2.2-1+pve1]
   # frr/stable 10.2.3-1+pve1 amd64 [upgradable from: 10.2.2-1+pve1]
   # so it get the text before the first / char
@@ -92,7 +143,7 @@ check_packages() {
 
   case "${os_name}" in 
   *Alpine*)
-    echo "I'm still learning how to upgrade the system in Alpine" | rainbow-notifytelegram
+    upgrade_on_alpine
     ;;
   *)
     upgrade_on_debian
